spring.application.name=authentication_api

#Config Base de donnees
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/authentication_api_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.security.key=sK3t4fN1V6y2aQ0QvE8J2k3mP6x9ZLhR8w4nXJYc9dE=,
jwt.expiration=86400000